### ISSUE TITLE
Add optional callback for cache evictions

### ISSUE THREAD

**Issue by voxpelli** [aholstenson/transitory#1]
An optional callback that's called with `key` and `value` whenever an item is dropped from cache would be very useful.

That way if one is keeping eg. an object in the cache up to date, by having it connected to some kind of update stream from a data store, then one can drop that connection once it's evicted from the cache.

**Comment by aholstenson** [comment]
:+1: Removal listeners can now be set. They receive three arguments, the key, the value and the removal cause.
