### ISSUE TITLE
Skip committed lockfile or something to keep dependabot less noisy?

### ISSUE THREAD

**Issue by voxpelli** [aholstenson/transitory#115]
I'm trying to watch this repo, in case some interesting PR or issue comes up that needs some attention, but so far practically everything I get is a ton of dependabot PR:s.

Something like #114 mostly creates noise, no?

An alternative would be to tweak what updates dependabot includes: https://dependabot.com/docs/config-file/#allowed_updates

And/or how often it checks for them: https://dependabot.com/docs/config-file/#update_schedule-required

A third alternative would be to use [Renovate](https://renovate.whitesourcesoftware.com/) instead, with something like this: https://github.com/voxpelli/renovate-config-voxpelli/blob/master/package.json

It reuses PR:s + groups PR:s together in a way that decreases the noise quite drastically.

**Comment by aholstenson** [comment]
`package-lock.json` has been removed from the repository, as well Depandabot being removed. At some point I'll get Renovate in here as it gives better control over the PRs.
