### ISSUE TITLE
cache.cleanUp() - An understanding

### ISSUE THREAD

**Issue by IParthJoshi** [aholstenson/transitory#121]
This is not an issue I created but wanna know more about the use of cache.cleanUp() in what I am using cache as Map<UUID, JwtToken>.
The desired output is I wanna use cache.cleanUp() inside a setInterval of few minutes and it would clean up each entry from the cache map on the basis of the expiry time of each individual token.
From what I see, .expireAfterTime() is on cache level and not individual entry then how would ".cleanUp()" actually cleans up each entry from cache on the basis of token expiry?

**Comment by aholstenson** [comment]
As you say `cleanUp()` is a maintenance method, it doesn't actually control expiration, but will check for expired items when run. Transitory will run `cleanUp()` on its own during normal use, but using it with a `setInterval` is useful for certain cases where you need to garbage collect more often.

To control expiration of individual items you can use a function with `expireAfterWrite` to set a custom expiration time based on the value. Something like this could work if your value contains a `Date` in a property `validUntil`:

```js
const cache = newCache()
  .expireAfterWrite((key, value) => value.validUntil.getTime() - Date.now())
  .build();
```

Or with `ExpirationCache` directly:

```js
const cache = new ExpirationCache({
  maxWriteAge: (key, value) => value.validUntil.getTime() - Date.now()
 
 parent: parentCacheHere
});
```
