### ISSUE TITLE
Loading Cache with expire after write can return an incorrect result.

### ISSUE THREAD

**Issue by MauriceGoodf** [aholstenson/transitory#122]
The code for the get method in the Loading cache contains the code:
>if (this.has(key)) {return Promise.resolve(this.getIfPresent(key) as V); }

The problem is that both has() and getIfPresent() call Date.now() to see if the item has expired. If Date.now() rolls over between these two calls, the one may decide that the entry is still valid, the second that it is not. This results in null being returned to the user.

What one would expect the code to do in this case is to try and load the value again if the cached entry has just expired.  Something like:
>const valueIfAlreadyPresent = this.getIfPresent(key);
if (valueIfAlreadyPresent != null) { return Promise.resolve(valueIfAlreadyPresent as V); }

**Comment by MauriceGoodf** [comment]
See pull request #133

**Comment by MauriceGoodf** [comment]
Also worrying that there is a version 2.1.1 on npm but the code version is 2.1.0

**Comment by MauriceGoodf** [comment]
I have had a look at the differences between 2.1.0 and 2.1.1 on npm and it appears  that the difference is a new version of Typescript plus the change to package.json.

**Comment by aholstenson** [comment]
A very long delay for me here, but a fix for this has been released with 2.2.0
