### ISSUE TITLE
README refers to a `done`, should that be `build` instead?

### ISSUE THREAD

**Issue by nlfiedler** [aholstenson/transitory#31]
Howdy, first off, thanks for this library. The only issue I have found so far after having used it for several months is that the README refers to a method called `done()` in the cache examples, but I can't find that in the source. I suspect that should be `build()` instead? Or I'm completely wrong, which happens quite often. Thanks.

**Comment by aholstenson** [comment]
Thanks for reporting this! And you're 100% correct, the README was wrong. Fixed.
